### ISSUE TITLE
Restivus.configure is not a function

### ISSUE THREAD

**Issue by shemeermali** [kahmali/meteor-restivus#291]
I am getting an error "Restivus.configure is not a function" on Meteor 1.6.1. The same code working fine in METEOR@1.1.0.2

My Code-:

```
Restivus.configure({
    prettyJson: true
  });
```

I have created new app in meteor and added restivus package using following command

`meteor add nimble:restivus`
Any idea?

Error details-:
```
TypeError: Restivus.configure is not a function
W20180227-15:02:32.766(5.5)? (STDERR)     at test.js (test.js:16:12)
W20180227-15:02:32.767(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180227-15:02:32.767(5.5)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180227-15:02:32.767(5.5)? (STDERR)     at /Applications/MAMP/htdocs/wuyers-api/.meteor/local/build/programs/server/app/app.js:234:1
W20180227-15:02:32.767(5.5)? (STDERR)     at /Applications/MAMP/htdocs/wuyers-api/.meteor/local/build/programs/server/boot.js:411:36
W20180227-15:02:32.767(5.5)? (STDERR)     at Array.forEach (<anonymous>)
W20180227-15:02:32.768(5.5)? (STDERR)     at /Applications/MAMP/htdocs/wuyers-api/.meteor/local/build/programs/server/boot.js:220:19
W20180227-15:02:32.768(5.5)? (STDERR)     at /Applications/MAMP/htdocs/wuyers-api/.meteor/local/build/programs/server/boot.js:471:5
W20180227-15:02:32.768(5.5)? (STDERR)     at Function.run (/Applications/MAMP/htdocs/wuyers-api/.meteor/local/build/programs/server/profile.js:510:12)
W20180227-15:02:32.768(5.5)? (STDERR)     at /Applications/MAMP/htdocs/wuyers-api/.meteor/local/build/programs/server/boot.js:470:11
```

Thanks

**Comment by shemeermali** [comment]
@kahmali, Can you please help me?
